import type { Project } from '@/types/project';

const initialTimestamp = '2026-08-22T00:00:00.000Z';

export const projects: Project[] = [
  {
    id: 'demo-ai-platform',
    slug: 'ai-platform-design',
    number: '01',
    year: '2026',
    category: 'AI 产品设计',
    title: 'AI 商品主图视觉系统',
    titleEn: 'AI Product Hero Visual System',
    description: '把生成式视觉、商业信息与可复用设计规则整合为高效率商品表达系统。',
    descriptionEn: 'An end-to-end AI workspace that transforms complex model capabilities into clear, dependable workflows.',
    value: '为智能功能建立可扩展的产品基础',
    tags: ['Product Design', 'AI Experience', 'UX Strategy'],
    services: ['产品策略', '交互设计', '原型设计', '设计系统'],
    coverImage: '/projects/project-01.png',
    imageBase: '/projects/project-01',
    images: ['/projects/project-01.png'],
    featured: true,
    sortOrder: 10,
    createdAt: initialTimestamp,
    updatedAt: initialTimestamp,
    overview: '为需要先进 AI 能力、又不希望被复杂提示词和技术细节打断的团队，设计一个冷静、可理解的协作工作空间。',
    challenge: '先进 AI 系统往往在用户最需要信心的时刻暴露过多技术复杂度。核心挑战，是在保留能力的同时减少决策疲劳、不透明状态与输出不确定性。',
    approach: '围绕用户意图而不是模型机制组织产品；从明确目标开始，仅在真正需要时逐步呈现高级控制，并持续让上下文、来源与系统状态保持可见。',
    outcome: '形成一套可持续扩展的 AI 体验基础。提示、审阅、来源与自动化模式能够被新功能复用，同时维持统一且可信的产品语言。',
    principles: ['意图先于界面', '可见性建立信任', '复杂度按需出现'],
  },
  {
    id: 'demo-commerce-system',
    slug: 'commerce-visual-system',
    number: '02',
    year: '2025',
    category: '电商视觉设计',
    title: '跨境电商 Listing 设计',
    titleEn: 'Cross-border Commerce Listing Design',
    description: '围绕卖点层级、视觉信任与移动端阅读节奏重塑跨境商品页面。',
    descriptionEn: 'An adaptive design system connecting AI discovery, personalization and content across the customer journey.',
    value: '更快速、更相关、更一致的商业体验',
    tags: ['Brand Experience', 'Design System', 'AI'],
    services: ['创意指导', '品牌系统', 'Commerce UX', '动效语言'],
    coverImage: '/projects/project-02.png',
    imageBase: '/projects/project-02',
    images: ['/projects/project-02.png'],
    featured: true,
    sortOrder: 20,
    createdAt: initialTimestamp,
    updatedAt: initialTimestamp,
    overview: '为不断变化的电商场景建立模块化视觉系统，在智能发现、个性化内容与产品叙事之间保持一致的品牌识别。',
    challenge: '个性化带来了不断增长的页面、活动与内容状态。缺少共同视觉逻辑时，体验会变得不一致，也难以跨市场和团队扩展。',
    approach: '用自适应模块替代固定模板。克制的字体、间距、色彩与动效构成统一节奏，生成式视觉方向则根据品类、意图和语境灵活变化。',
    outcome: '品牌与产品团队获得共同的创作语言，在更快生产相关体验的同时，让品牌通过规则与行为维持稳定识别。',
    principles: ['系统而非模板', '行为塑造识别', '个性化但不制造噪音'],
  },
  {
    id: 'demo-saas-experience',
    slug: 'saas-product-experience',
    number: '03',
    year: '2024',
    category: 'SaaS 产品',
    title: 'AI SaaS 产品界面',
    titleEn: 'AI SaaS Product Experience',
    description: '围绕清晰层级、智能工作流与可复用模式重塑复杂 AI SaaS 体验。',
    descriptionEn: 'A scalable SaaS experience shaped around clear hierarchy, focused workflows and reusable interface patterns.',
    value: '让复杂产品在团队扩张中保持一致',
    tags: ['SaaS', 'UI/UX', 'Product Systems'],
    services: ['信息架构', '产品设计', '前端开发', '设计系统'],
    coverImage: '/projects/project-03.png',
    imageBase: '/projects/project-03',
    images: ['/projects/project-03.png'],
    featured: true,
    sortOrder: 30,
    createdAt: initialTimestamp,
    updatedAt: initialTimestamp,
    overview: '为功能快速增长的数据型 SaaS 平台重构产品体验，帮助用户理解真正重要的信息，并在概览与细节之间顺畅行动。',
    challenge: '多年功能增长带来密集导航、不一致交互与高学习成本，同时团队缺少支持新能力持续交付的共同界面基础。',
    approach: '以用户需要完成的决策重新组织信息架构，合并重复模式，并把结果转化为具备明确内容和行为规则的生产级组件。',
    outcome: '复杂工作变得更有结构、更可预测；共享系统同时提升用户体验的一致性与产品团队扩展功能的速度。',
    principles: ['层级创造速度', '模式建立信心', '扩展而不漂移'],
  },
  {
    id: 'demo-portfolio-experience',
    slug: 'personal-brand-portfolio',
    number: '04',
    year: '2026',
    category: '前端开发',
    title: '个人品牌 Portfolio 网站',
    titleEn: 'Personal Brand Portfolio Experience',
    description: '将个人能力、项目价值与合作转化整合为具有品牌辨识度的数字体验。',
    descriptionEn: 'A high-conversion personal brand experience built around work, point of view and creative technology.',
    value: '让专业能力在 30 秒内被理解',
    tags: ['Next.js', 'Creative Dev', 'Motion'],
    services: ['产品策略', '视觉设计', '前端开发', '动效设计'],
    coverImage: '/projects/project-04.png',
    images: ['/projects/project-04.png'],
    featured: true,
    sortOrder: 40,
    createdAt: initialTimestamp,
    updatedAt: initialTimestamp,
    overview: '以清晰的个人叙事、沉浸式案例展示和克制动效建立能够持续迭代的数字品牌主页。',
    challenge: '传统作品集容易陷入简历化与模板化，无法快速传达专业判断、跨学科能力和合作价值。',
    approach: '从访客的决策路径出发组织内容，用高对比排版、重点案例和动效反馈建立节奏，同时保证移动端性能和可访问性。',
    outcome: '形成一套兼具展示、沟通与内容管理能力的长期个人品牌基础设施。',
    principles: ['价值先于经历', '作品承担证明', '动效服务叙事'],
  },
  {
    id: 'demo-commerce-detail',
    slug: 'commerce-detail-redesign',
    number: '05',
    year: '2025',
    category: '电商视觉设计',
    title: '电商详情页视觉升级',
    titleEn: 'E-commerce Detail Page Redesign',
    description: '通过视觉层级、场景内容与模块化模板提升商品理解、品牌感和转化表达。',
    descriptionEn: 'A modular commerce story that improves product clarity, visual trust and conversion intent.',
    value: '从信息堆积升级为品牌叙事',
    tags: ['E-commerce', 'Visual System', 'Conversion'],
    services: ['视觉策略', '内容结构', '商品视觉', '模板系统'],
    coverImage: '/projects/project-05.png',
    images: ['/projects/project-05.png'],
    featured: true,
    sortOrder: 50,
    createdAt: initialTimestamp,
    updatedAt: initialTimestamp,
    overview: '为多 SKU 商品建立高一致性、高效率的详情页视觉框架，在移动端快速传达核心价值。',
    challenge: '不同商品页面缺少统一层级，卖点被大量素材淹没，品牌识别和内容生产效率同时受限。',
    approach: '重新排列购买决策所需信息，建立适用于不同品类的内容模块，并通过统一光影、色彩和字体规则强化品牌。',
    outcome: '页面阅读路径更明确，内容制作更可复用，商品与品牌之间形成更稳定的视觉关联。',
    principles: ['先解决理解', '模块支持规模', '视觉建立信任'],
  },
  {
    id: 'demo-digital-brand',
    slug: 'digital-brand-website',
    number: '06',
    year: '2025',
    category: '品牌视觉设计',
    title: '数字品牌官网设计',
    titleEn: 'Digital Brand Website System',
    description: '连接品牌识别、响应式界面与内容组件，打造可持续扩展的数字品牌官网。',
    descriptionEn: 'A scalable digital brand system spanning identity, responsive interfaces and reusable content modules.',
    value: '让品牌在每个数字触点保持一致',
    tags: ['Brand', 'Web Design', 'Design System'],
    services: ['品牌策略', '数字视觉', '网站设计', '设计系统'],
    coverImage: '/projects/project-06.png',
    images: ['/projects/project-06.png'],
    featured: true,
    sortOrder: 60,
    createdAt: initialTimestamp,
    updatedAt: initialTimestamp,
    overview: '为新一代数字业务建立鲜明而克制的品牌官网，在表达专业感的同时支持长期内容增长。',
    challenge: '品牌资产分散，网站页面之间缺少统一的视觉和交互逻辑，新内容上线往往依赖重复设计。',
    approach: '把品牌原则翻译为数字组件、响应式规则和动效语言，让每个页面都具有识别度又能高效扩展。',
    outcome: '形成统一的品牌体验与内容生产基础，团队能够更快上线页面，同时保持视觉质量。',
    principles: ['识别来自规则', '组件承载品牌', '一致而不单调'],
  },
];

export type { Project } from '@/types/project';

export function getFallbackProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}
