'use client';

import { Search, Trash2, UserPlus } from 'lucide-react';
import { useMemo, useState } from 'react';
import { createUserAction, deleteUserAction, updateUserAction } from '@/app/admin/cms-actions';
import { Field, adminButton, adminCard, adminInput, adminSecondaryButton } from '@/components/admin/admin-ui';
import { PortfolioImage } from '@/components/portfolio-image';
import type { CmsProfile } from '@/types/cms';

export function UsersManager({ users, currentUserId }: { users: CmsProfile[]; currentUserId?: string }) {
  const [query, setQuery] = useState(''); const [role, setRole] = useState('all'); const [creating, setCreating] = useState(false);
  const filtered = useMemo(() => users.filter((user) => (role === 'all' || user.role === role) && `${user.displayName} ${user.email}`.toLowerCase().includes(query.toLowerCase())), [users, query, role]);
  return <div className="space-y-4">
    <div className="flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={14} /><input className="h-10 w-full rounded-[8px] border border-border bg-card pl-9 pr-3 text-sm outline-none" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索名称或邮箱…" /></label><select className="h-10 rounded-[8px] border border-border bg-card px-3 text-sm" value={role} onChange={(event) => setRole(event.target.value)}><option value="all">全部角色</option><option value="admin">Admin</option><option value="editor">Editor</option><option value="user">User</option></select><button className={adminButton} onClick={() => setCreating((value) => !value)}><UserPlus size={14} /> 新增用户</button></div>
    {creating ? <form action={createUserAction} className={adminCard}><h3 className="text-sm font-semibold">创建后台用户</h3><p className="mt-1 text-xs text-muted-foreground">账号会在 Supabase Auth 中创建并立即确认邮箱。</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="显示名称"><input className={adminInput} name="displayName" required /></Field><Field label="邮箱"><input className={adminInput} type="email" name="email" required /></Field><Field label="初始密码"><input className={adminInput} type="password" name="password" minLength={8} required /></Field><Field label="头像 URL"><input className={adminInput} name="avatarUrl" /></Field><Field label="角色"><select className={adminInput} name="role" defaultValue="editor"><option value="admin">Admin</option><option value="editor">Editor</option><option value="user">User</option></select></Field></div><div className="mt-4 flex justify-end"><button className={adminButton}><UserPlus size={14} /> 创建账号</button></div></form> : null}
    {filtered.length ? <div className="space-y-3">{filtered.map((user) => <form action={updateUserAction} key={user.id} className={adminCard}><input type="hidden" name="id" value={user.id} /><div className="flex items-start gap-3"><div className="relative flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-full bg-violet-500/10 text-sm font-semibold text-violet-500">{user.avatarUrl ? <PortfolioImage src={user.avatarUrl} alt="" fill sizes="44px" className="object-cover" /> : (user.displayName || user.email).slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{user.email}</p><p className="mt-1 text-[9px] uppercase tracking-[.1em] text-muted-foreground">创建 {new Date(user.createdAt).toLocaleDateString('zh-CN')} · 最后登录 {user.lastSignInAt ? new Date(user.lastSignInAt).toLocaleString('zh-CN') : '—'}</p></div><span className={`rounded-full px-2.5 py-1 text-[9px] ${user.status === 'active' ? 'bg-emerald-500/10 text-emerald-600' : 'bg-red-500/10 text-red-500'}`}>{user.status === 'active' ? '正常' : '禁用'}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_1.2fr_140px_140px_auto]"><Field label="名称"><input className={adminInput} name="displayName" defaultValue={user.displayName || user.email.split('@')[0]} required /></Field><Field label="头像 URL"><input className={adminInput} name="avatarUrl" defaultValue={user.avatarUrl} /></Field><Field label="角色"><select className={adminInput} name="role" defaultValue={user.role} disabled={user.id === currentUserId}><option value="admin">Admin</option><option value="editor">Editor</option><option value="user">User</option></select>{user.id === currentUserId ? <input type="hidden" name="role" value="admin" /> : null}</Field><Field label="状态"><select className={adminInput} name="status" defaultValue={user.status} disabled={user.id === currentUserId}><option value="active">正常</option><option value="disabled">禁用</option></select>{user.id === currentUserId ? <input type="hidden" name="status" value="active" /> : null}</Field><div className="flex items-end gap-2"><button className={adminSecondaryButton}>保存</button>{user.id !== currentUserId ? <button formAction={deleteUserAction} onClick={(event) => { if (!window.confirm(`确认删除 ${user.email}？此操作不可恢复。`)) event.preventDefault(); }} className="inline-flex size-10 items-center justify-center rounded-[8px] border border-red-500/20 text-red-500" aria-label={`删除 ${user.email}`}><Trash2 size={14} /></button> : null}</div></div></form>)}</div> : <div className="rounded-[14px] border border-dashed border-border py-20 text-center"><p className="text-sm font-medium">没有匹配的用户</p><p className="mt-2 text-xs text-muted-foreground">调整搜索或角色筛选。</p></div>}
  </div>;
}
