import { Save } from 'lucide-react';
import { savePageContentAction } from '@/app/admin/cms-actions';
import { AdminNotice, AdminPageIntro, Field, adminButton, adminCard, adminInput, adminTextarea } from '@/components/admin/admin-ui';
import { getCmsConfig } from '@/lib/supabase/cms';

export const dynamic = 'force-dynamic';

export default async function ContentPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const [cms, params] = await Promise.all([getCmsConfig(), searchParams]);
  const { hero, about, contact, footer, sectionHeadings } = cms;
  return <div><AdminPageIntro eyebrow="Content management" title="页面内容" description="集中维护首页、关于、联系与页脚的中英文内容。保存后前台刷新即可生效。" /><AdminNotice status={params.status} />
    <form action={savePageContentAction} className="space-y-4">
      <section className={adminCard}><h3 className="text-base font-semibold">首页 Hero</h3><p className="mt-1 text-xs text-muted-foreground">主视觉、标题、说明与两个行动按钮。</p><div className="mt-5 grid gap-4 sm:grid-cols-2">
        <Field label="中文小标题"><input className={adminInput} name="heroEyebrowZh" defaultValue={hero.eyebrow.zh} required /></Field><Field label="English eyebrow"><input className={adminInput} name="heroEyebrowEn" defaultValue={hero.eyebrow.en} required /></Field>
        <Field label="中文主标题" hint="可换行"><textarea className={adminTextarea} name="heroTitleZh" defaultValue={hero.title.zh} required /></Field><Field label="English title"><textarea className={adminTextarea} name="heroTitleEn" defaultValue={hero.title.en} required /></Field>
        <Field label="中文副标题"><textarea className={adminTextarea} name="heroSubtitleZh" defaultValue={hero.subtitle.zh} required /></Field><Field label="English subtitle"><textarea className={adminTextarea} name="heroSubtitleEn" defaultValue={hero.subtitle.en} required /></Field>
        <Field label="主按钮中文"><input className={adminInput} name="primaryLabelZh" defaultValue={hero.primaryLabel.zh} required /></Field><Field label="Primary button"><input className={adminInput} name="primaryLabelEn" defaultValue={hero.primaryLabel.en} required /></Field>
        <Field label="主按钮链接"><input className={adminInput} name="primaryHref" defaultValue={hero.primaryHref} required /></Field><Field label="次按钮链接"><input className={adminInput} name="secondaryHref" defaultValue={hero.secondaryHref} required /></Field>
        <Field label="次按钮中文"><input className={adminInput} name="secondaryLabelZh" defaultValue={hero.secondaryLabel.zh} required /></Field><Field label="Secondary button"><input className={adminInput} name="secondaryLabelEn" defaultValue={hero.secondaryLabel.en} required /></Field>
        <Field label="人物视觉 URL" hint="可从媒体资源复制链接"><input className={adminInput} name="portrait" defaultValue={hero.portrait} required /></Field>
      </div></section>
      <section className={adminCard}><h3 className="text-base font-semibold">关于我</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="中文标题"><input className={adminInput} name="aboutTitleZh" defaultValue={about.title.zh} required /></Field><Field label="English title"><input className={adminInput} name="aboutTitleEn" defaultValue={about.title.en} required /></Field><Field label="中文介绍"><textarea className={adminTextarea} name="aboutDescriptionZh" defaultValue={about.description.zh} required /></Field><Field label="English introduction"><textarea className={adminTextarea} name="aboutDescriptionEn" defaultValue={about.description.en} required /></Field></div></section>
      <section className={adminCard}><h3 className="text-base font-semibold">模块介绍</h3><p className="mt-1 text-xs text-muted-foreground">服务、作品与技能区域的标题和简短说明。</p><div className="mt-5 grid gap-4 sm:grid-cols-2">
        <Field label="服务标题（中文）"><input className={adminInput} name="servicesTitleZh" defaultValue={sectionHeadings.servicesTitle.zh} required /></Field><Field label="Services title"><input className={adminInput} name="servicesTitleEn" defaultValue={sectionHeadings.servicesTitle.en} required /></Field><Field label="服务说明（中文）"><textarea className={adminTextarea} name="servicesDescriptionZh" defaultValue={sectionHeadings.servicesDescription.zh} required /></Field><Field label="Services description"><textarea className={adminTextarea} name="servicesDescriptionEn" defaultValue={sectionHeadings.servicesDescription.en} required /></Field>
        <Field label="作品标题（中文）"><input className={adminInput} name="workTitleZh" defaultValue={sectionHeadings.workTitle.zh} required /></Field><Field label="Work title"><input className={adminInput} name="workTitleEn" defaultValue={sectionHeadings.workTitle.en} required /></Field><Field label="作品说明（中文）"><textarea className={adminTextarea} name="workDescriptionZh" defaultValue={sectionHeadings.workDescription.zh} required /></Field><Field label="Work description"><textarea className={adminTextarea} name="workDescriptionEn" defaultValue={sectionHeadings.workDescription.en} required /></Field>
        <Field label="技能标题（中文）"><input className={adminInput} name="skillsTitleZh" defaultValue={sectionHeadings.skillsTitle.zh} required /></Field><Field label="Skills title"><input className={adminInput} name="skillsTitleEn" defaultValue={sectionHeadings.skillsTitle.en} required /></Field><Field label="技能说明（中文）"><textarea className={adminTextarea} name="skillsDescriptionZh" defaultValue={sectionHeadings.skillsDescription.zh} required /></Field><Field label="Skills description"><textarea className={adminTextarea} name="skillsDescriptionEn" defaultValue={sectionHeadings.skillsDescription.en} required /></Field>
      </div></section>
      <section className={adminCard}><h3 className="text-base font-semibold">联系与页脚</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="联系小标题（中文）"><input className={adminInput} name="contactEyebrowZh" defaultValue={contact.eyebrow.zh} required /></Field><Field label="Contact eyebrow"><input className={adminInput} name="contactEyebrowEn" defaultValue={contact.eyebrow.en} required /></Field><Field label="联系标题（中文）"><input className={adminInput} name="contactTitleZh" defaultValue={contact.title.zh} required /></Field><Field label="Contact title"><input className={adminInput} name="contactTitleEn" defaultValue={contact.title.en} required /></Field><Field label="联系说明（中文）"><textarea className={adminTextarea} name="contactDescriptionZh" defaultValue={contact.description.zh} required /></Field><Field label="Contact description"><textarea className={adminTextarea} name="contactDescriptionEn" defaultValue={contact.description.en} required /></Field><Field label="页脚中文"><input className={adminInput} name="footerZh" defaultValue={footer.zh} required /></Field><Field label="Footer English"><input className={adminInput} name="footerEn" defaultValue={footer.en} required /></Field></div></section>
      <div className="sticky bottom-4 flex justify-end"><button className={`${adminButton} shadow-lg`}><Save size={15} /> 保存全部内容</button></div>
    </form>
  </div>;
}
